services:
  g-cloud:
    build: .
    container_name: g-cloud-v1
    restart: unless-stopped
    
    # Vital para que detecte la red USB de la GoPro
    network_mode: host
    
    # Para poder leer dispositivos USB y montar discos
    privileged: true
    
    volumes:
      # 1. Persistencia de datos (Todo se guarda aquí para evitar el bug de las carpetas fantasma)
      - ./data:/app/data
      
      # 2. Acceso a los Discos Duros y memorias USB
      - /media:/media
      - /mnt:/mnt